spring:
  datasource:
    name: defaultDataSource
    password: 153500552ALI@COM
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: foo
    url: jdbc:mysql://rm-bp15z0b6lr0m8utpeqo.mysql.rds.aliyuncs.com:3306/oauth2-check-token-jdbc?serverTimezone=UTC